In [66]:
import numpy as np
from random import randint

In [67]:
mat = np.array([[randint(1,20) for _ in range(5)] for _ in range(20)])
mat

array([[ 7,  2, 17,  8,  4],
       [ 4,  5, 17,  7,  4],
       [ 3,  5, 12,  4,  7],
       [10, 13, 19,  1,  7],
       [19, 13,  8,  6, 15],
       [19, 20,  3, 15,  6],
       [16,  8, 11,  7,  3],
       [ 2, 11, 14, 10, 20],
       [14, 15, 10, 19,  3],
       [ 6, 13,  5,  2, 20],
       [15, 10,  6, 13,  7],
       [ 3, 18,  2,  1,  3],
       [14,  9, 15,  5, 12],
       [13,  3, 14, 17,  7],
       [11, 10, 20,  7, 19],
       [16, 14, 18, 17,  7],
       [ 6,  3,  2, 13, 13],
       [18, 11, 19, 19, 14],
       [15,  4, 16, 12,  7],
       [ 9, 17, 20, 18,  4]])

In [68]:
means = np.mean(mat, axis=0)
means

array([ 11.  ,  10.2 ,  12.4 ,  10.05,   9.1 ])

In [69]:
diff = np.array([i-means for i in mat])

In [70]:
t = diff.transpose()

In [71]:
cov = np.dot(diff,t)

In [72]:
cov/4

array([[  3.36531250e+01,   3.10156250e+01,   2.39781250e+01,
          1.01656250e+01,  -2.42468750e+01,  -3.74843750e+01,
          7.24062500e+00,  -4.67187500e+00,  -1.24093750e+01,
         -1.90218750e+01,  -9.78437500e+00,  -7.53437500e+00,
          1.34062500e+00,   1.37156250e+01,  -1.90937500e+00,
         -7.23437500e+00,   1.31562500e+00,  -1.18843750e+01,
          1.45281250e+01,  -7.71875000e-01],
       [  3.10156250e+01,   3.31281250e+01,   2.75906250e+01,
          1.52781250e+01,  -2.71343750e+01,  -3.73718750e+01,
          2.60312500e+00,   2.69062500e+00,  -1.32968750e+01,
         -1.11593750e+01,  -1.36718750e+01,   6.57812500e+00,
         -5.46875000e-01,   5.07812500e+00,  -1.29687500e+00,
         -9.87187500e+00,  -1.07187500e+00,  -1.87718750e+01,
          6.39062500e+00,   3.84062500e+00],
       [  2.39781250e+01,   2.75906250e+01,   3.30531250e+01,
          1.24906250e+01,  -1.61718750e+01,  -3.36593750e+01,
          8.15625000e-01,   1.11531250e+01

In [73]:
np.cov(mat)

array([[  3.33000000e+01,   2.94500000e+01,   1.48500000e+01,
          1.87500000e+01,  -1.51500000e+01,  -2.77000000e+01,
          1.02500000e+01,   2.00000000e-01,  -4.00000000e-01,
         -2.51500000e+01,  -7.15000000e+00,  -2.35500000e+01,
          1.02500000e+01,   2.21500000e+01,   1.49500000e+01,
          1.57000000e+01,  -1.08000000e+01,   1.58500000e+01,
          2.46500000e+01,   2.00500000e+01],
       [  2.94500000e+01,   3.03000000e+01,   1.69000000e+01,
          2.32500000e+01,  -1.81000000e+01,  -2.75500000e+01,
          4.75000000e+00,   7.30000000e+00,  -1.35000000e+00,
         -1.81000000e+01,  -1.16000000e+01,  -1.12000000e+01,
          8.00000000e+00,   1.31000000e+01,   1.58000000e+01,
          1.35500000e+01,  -1.44500000e+01,   9.90000000e+00,
          1.61000000e+01,   2.49500000e+01],
       [  1.48500000e+01,   1.69000000e+01,   1.27000000e+01,
          1.65000000e+01,  -7.80000000e+00,  -2.39000000e+01,
         -2.50000000e+00,   1.39000000e+01