## Pair Programming - Matrices
Kenneth and Kenneth

In [2]:
import numpy as np

In [46]:
x =[[5,3,7],[2,4,1]]
y = [[537],[241]]

In [56]:
a = np.array(x)
b = np.array(y)

print a, b

[[2 4]
 [0 1]] [8 3]


In [57]:
aT = a.transpose()
aT

array([[2, 0],
       [4, 1]])

In [58]:
aTai = np.linalg.inv(aT * a)
aTai

array([[ 0.25,  0.  ],
       [ 0.  ,  1.  ]])

In [59]:
print aTai.shape
print aT.shape
print b.shape



(2, 2)
(2, 2)
(2,)


In [61]:
aTai * (aT * b)

array([[ 4.,  0.],
       [ 0.,  3.]])

In [55]:
x = [[2,4],[0,1]]
y = [8,3]

try:
    print np.linalg.solve(x,y)
except:
    print 'no solution'

[-2.  3.]
